import fs from 'fs/promises';
import path from 'path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { ProviderManager } from './ProviderManager.js';

interface Tool {
  name: string;
  description?: string;
  inputSchema?: {
    type?: string;
    properties?: Record<string, unknown>;
    required?: string[];
  };
}

export class ToolDocumenter {
  // We'll try to resolve to the project root.
  private static get STORAGE_PATH() {
    let root = process.cwd();
    if (root.endsWith('apps/api')) {
        root = path.resolve(root, '../../');
    }
    return path.resolve(root, '.domoreai/tools');
  }

  static async documentServer(serverName: string, client: Client) {
    try {
      // Ensure directory exists
      await fs.mkdir(this.STORAGE_PATH, { recursive: true });

      const result = await client.listTools();
      const tools = result.tools as Tool[];
      
      if (!tools || tools.length === 0) return;

      // 1. Generate Type Definitions
      const typeDefs = this.generateTypeDefinitions(serverName, tools);
      await fs.writeFile(path.join(this.STORAGE_PATH, `${serverName}.d.ts`), typeDefs);

      // 2. Generate Usage Examples
      const examples = await this.generateUsageExamples(serverName, tools);
      await fs.writeFile(path.join(this.STORAGE_PATH, `${serverName}_examples.md`), examples);
      
      console.log(`[ToolDocumenter] Generated documentation for ${serverName}`);
    } catch (error) {
      console.error(`[ToolDocumenter] Failed to document server ${serverName}:`, error);
    }
  }

  private static generateTypeDefinitions(serverName: string, tools: Tool[]): string {
    const lines: string[] = [];
    
    lines.push(`// Type definitions for ${serverName}`);
    lines.push(`// Generated by ToolDocumenter`);
    lines.push('');
    lines.push('declare namespace system {');

    for (const tool of tools) {
      const toolName = `${serverName}_${tool.name}`;
      const interfaceName = `${this.capitalize(serverName)}${this.capitalize(tool.name)}Args`;
      
      // Generate Interface from JSON Schema
      const schema = tool.inputSchema;
      const props: string[] = [];
      
      if (schema && schema.properties) {
        for (const [key, value] of Object.entries(schema.properties)) {
          // Cast value to any or check type
          if (typeof value === 'object' && value !== null && 'type' in (value as any)) {
            const isOptional = !schema.required?.includes(key);
            const type = this.mapJsonTypeToTs((value as any).type);
            props.push(`    ${key}${isOptional ? '?' : ''}: ${type};`);
          }
        }
      }

      lines.push(`  interface ${interfaceName} {`);
      lines.push(props.join('\n'));
      lines.push(`  }`);
      lines.push('');
      lines.push(`  /**`);
      lines.push(`   * ${tool.description || 'No description provided.'}`);
      lines.push(`   */`);
      lines.push(`  function ${toolName}(args: ${interfaceName}): Promise<any>;`);
      lines.push('');
    }

    lines.push('}');
    return lines.join('\n');
  }

  private static async generateUsageExamples(serverName: string, tools: Tool[]): Promise<string> {
    const examples: string[] = [];

    // We'll try to get a smart model to generate examples
    // If we can't, we'll generate a basic template
    let model = null;
    try {
        // Try to find a model that supports reasoning or coding
        // We'll just ask for a generic best model for 'coding' role if possible, or just any model
        // Since we don't have a role ID handy, we'll try to find a default model
        const allModels = await ProviderManager.getAllModels();
        model = allModels.find(m => m.id.includes('claude-3-5') || m.id.includes('gpt-4'));
    } catch (e) {
        // Ignore
    }

    for (const tool of tools) {
      const toolName = `${serverName}_${tool.name}`;
      
      let exampleCode = `await system.${toolName}({ /* args */ });`;

      if (model) {
        try {
            const provider = ProviderManager.getProvider(model.providerId);
            if (provider) {
                const prompt = `
                You are an expert TypeScript developer.
                I have a tool named "${toolName}".
                Description: ${tool.description}
                Input Schema: ${JSON.stringify(tool.inputSchema)}

                Write a 1-sentence Code Mode example of how to call this tool using await system.${toolName}(...).
                Do not include markdown code blocks, just the code line.
                `;

                const response = await provider.generateCompletion({
                    modelId: model.id,
                    messages: [{ role: 'user', content: prompt }],
                    temperature: 0.2,
                    max_tokens: 100
                });
                
                exampleCode = response.trim().replace(/`/g, '');
            }
        } catch (e) {
            console.warn(`[ToolDocumenter] Failed to generate smart example for ${toolName}`, e);
        }
      }

      examples.push(`// Tool: ${toolName}`);
      examples.push(`// Usage: ${exampleCode}`);
      examples.push('');
    }

    return examples.join('\n');
  }

  private static capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  private static mapJsonTypeToTs(type: string): string {
    switch (type) {
      case 'string': return 'string';
      case 'integer': return 'number';
      case 'number': return 'number';
      case 'boolean': return 'boolean';
      case 'array': return 'any[]';
      case 'object': return 'any';
      default: return 'any';
    }
  }
}
