
import React from 'react';
import { useAudioPlayer } from '../hooks/useAudioPlayer';
import { Button } from './ui/button'; // Assuming you have a Button component from shadcn/ui

interface AudioPlayerProps {
  src: string;
}

/**
 * An audio player component that can be used to play audio from a given URL.
 *
 * @param src The URL of the audio file to play. This would typically be a URL
 *            to an audio file generated by a text-to-speech service like Coqui TTS.
 *
 * @example
 *
 * import AudioPlayer from './AudioPlayer';
 *
 * const MyComponent = () => {
 *   const audioUrl = 'http://localhost:4000/path/to/your/audio.wav';
 *   return (
 *     <div>
 *       <h1>My Audio Player</h1>
 *       <AudioPlayer src={audioUrl} />
 *     </div>
  *   );
 * }
 */
const AudioPlayer: React.FC<AudioPlayerProps> = ({ src }) => {
  const { play, pause, stop, seek, isPlaying, duration, currentTime, isLoaded } = useAudioPlayer(src);

  const formatTime = (time: number) => {
    const minutes = Math.floor(time / 60);
    const seconds = Math.floor(time % 60).toString().padStart(2, '0');
    return `${minutes}:${seconds}`;
  };

  return (
    <div className="flex items-center gap-4 p-4 border rounded-lg">
      <div className="flex gap-2">
        <Button onClick={play} disabled={!isLoaded || isPlaying}>
          Play
        </Button>
        <Button onClick={pause} disabled={!isLoaded || !isPlaying}>
          Pause
        </Button>
        <Button onClick={stop} disabled={!isLoaded}>
          Stop
        </Button>
      </div>
      <div className="flex-grow">
        <input
          type="range"
          min="0"
          max={duration}
          value={currentTime}
          className="w-full"
          disabled={!isLoaded}
          onChange={(e) => {
            const time = Number(e.target.value);
            seek(time);
          }}
        />
        <div className="flex justify-between text-xs">
          <span>{formatTime(currentTime)}</span>
          <span>{formatTime(duration)}</span>
        </div>
      </div>
    </div>
  );
};

export default AudioPlayer;
