import type { Theme } from './types.js';

// Neon color definitions
const neonColors = {
  cyan: { name: 'Cyan', value: '#00FFFF', glow: '0 0 20px rgba(0, 255, 255, 0.8)' },
  magenta: { name: 'Magenta', value: '#FF00FF', glow: '0 0 20px rgba(255, 0, 255, 0.8)' },
  yellow: { name: 'Yellow', value: '#FFFF00', glow: '0 0 20px rgba(255, 255, 0, 0.8)' },
  green: { name: 'Green', value: '#00FF00', glow: '0 0 20px rgba(0, 255, 0, 0.8)' },
  orange: { name: 'Orange', value: '#FF6600', glow: '0 0 20px rgba(255, 102, 0, 0.8)' },
  purple: { name: 'Purple', value: '#9D00FF', glow: '0 0 20px rgba(157, 0, 255, 0.8)' },
  pink: { name: 'Pink', value: '#FF1493', glow: '0 0 20px rgba(255, 20, 147, 0.8)' },
  blue: { name: 'Blue', value: '#0080FF', glow: '0 0 20px rgba(0, 128, 255, 0.8)' },
};

const baseTheme = {
  colors: {
    primary: neonColors.cyan,
    secondary: neonColors.purple,
    accent: neonColors.magenta,
    success: neonColors.green,
    warning: neonColors.yellow,
    error: neonColors.pink,
    info: neonColors.blue,
    // Background and text colors
    background: '#000000',
    backgroundSecondary: '#0a0a0a',
    text: '#ffffff',
    textSecondary: '#a0a0a0',
    textMuted: '#606060',
    border: '#1a1a1a',
  },
};

export const lightTheme: Theme = {
  preset: 'light',
  colors: {
    primary: { name: 'Cyan', value: '#0080a0', glow: '0 0 10px rgba(0, 128, 160, 0.5)' },
    secondary: { name: 'Purple', value: '#6B00A0', glow: '0 0 10px rgba(107, 0, 160, 0.5)' },
    accent: { name: 'Magenta', value: '#A00080', glow: '0 0 10px rgba(160, 0, 128, 0.5)' },
    success: { name: 'Green', value: '#008000', glow: '0 0 10px rgba(0, 128, 0, 0.5)' },
    warning: { name: 'Orange', value: '#CC5500', glow: '0 0 10px rgba(204, 85, 0, 0.5)' },
    error: { name: 'Red', value: '#CC0033', glow: '0 0 10px rgba(204, 0, 51, 0.5)' },
    info: { name: 'Blue', value: '#0060C0', glow: '0 0 10px rgba(0, 96, 192, 0.5)' },
    background: '#ffffff',
    backgroundSecondary: '#f5f5f5',
    text: '#1a1a1a',
    textSecondary: '#505050',
    textMuted: '#808080',
    border: '#d0d0d0',
  },
  visual: {
    textBrightness: 100,
    borderBrightness: 100,
    backgroundDarkness: 0,
    glowIntensity: 20,
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.5,
    letterSpacing: 0,
    borderWidth: 1,
    borderGlow: false,
    transparency: 0,
    blurEffects: false,
  },
  animations: {
    enabled: true,
    speed: 1,
    hoverEffectsIntensity: 20,
    transitionDuration: 200,
    particleEffects: false,
    screenShake: false,
  },
  sounds: {
    enabled: false,
    volume: 50,
    clickSound: false,
    hoverSound: false,
    successSound: false,
    errorSound: false,
  },
  widgets: {
    clock: { enabled: false, style: 'digital', size: 'small' },
    newsFeed: { enabled: false, speed: 5, source: '' },
    logo: { enabled: false, type: 'custom', animated: false, size: 'small' },
    systemStats: { enabled: false, metrics: [] },
  },
  layout: {
    menuStyle: 'standard',
    iconTheme: 'outline',
    density: 'normal',
    spacingMultiplier: 1,
    gapSize: 12,
  },
};

export const minimalTheme: Theme = {
  preset: 'minimal',
  ...baseTheme,
  visual: {
    textBrightness: 100,
    borderBrightness: 100,
    backgroundDarkness: 0,
    glowIntensity: 30,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 1.5,
    letterSpacing: 0,
    borderWidth: 2,
    borderGlow: true,
    transparency: 0,
    blurEffects: false,
  },
  animations: {
    enabled: true,
    speed: 1,
    hoverEffectsIntensity: 20,
    transitionDuration: 200,
    particleEffects: false,
    screenShake: false,
  },
  sounds: {
    enabled: false,
    volume: 50,
    clickSound: false,
    hoverSound: false,
    successSound: false,
    errorSound: false,
  },
  widgets: {
    clock: { enabled: false, style: 'digital', size: 'small' },
    newsFeed: { enabled: false, speed: 5, source: '' },
    logo: { enabled: false, type: 'custom', animated: false, size: 'small' },
    systemStats: { enabled: false, metrics: [] },
  },
  layout: {
    menuStyle: 'compact',
    iconTheme: 'outline',
    density: 'normal',
    spacingMultiplier: 1,
    gapSize: 8,
  },
};

export const standardTheme: Theme = {
  preset: 'standard',
  ...baseTheme,
  colors: {
    ...baseTheme.colors,
    primary: neonColors.purple,
    secondary: neonColors.blue,
    accent: neonColors.cyan,
    success: neonColors.green,
    warning: neonColors.yellow,
    error: neonColors.pink,
    info: neonColors.blue,
  },
  visual: {
    textBrightness: 100,
    borderBrightness: 100,
    backgroundDarkness: 5,
    glowIntensity: 50,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.5,
    letterSpacing: 0.5,
    borderWidth: 2,
    borderGlow: true,
    transparency: 10,
    blurEffects: true,
  },
  animations: {
    enabled: true,
    speed: 1.2,
    hoverEffectsIntensity: 50,
    transitionDuration: 250,
    particleEffects: false,
    screenShake: false,
  },
  sounds: {
    enabled: false,
    volume: 50,
    clickSound: false,
    hoverSound: false,
    successSound: true,
    errorSound: true,
  },
  widgets: {
    clock: { enabled: true, style: 'digital', size: 'small' },
    newsFeed: { enabled: false, speed: 5, source: '' },
    logo: { enabled: false, type: 'custom', animated: false, size: 'small' },
    systemStats: { enabled: false, metrics: [] },
  },
  layout: {
    menuStyle: 'standard',
    iconTheme: 'outline',
    density: 'normal',
    spacingMultiplier: 1,
    gapSize: 12,
  },
};

export const flashyTheme: Theme = {
  preset: 'flashy',
  ...baseTheme,
  visual: {
    textBrightness: 100,
    borderBrightness: 100,
    backgroundDarkness: 10,
    glowIntensity: 80,
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1.6,
    letterSpacing: 1,
    borderWidth: 3,
    borderGlow: true,
    transparency: 20,
    blurEffects: true,
  },
  animations: {
    enabled: true,
    speed: 1.5,
    hoverEffectsIntensity: 80,
    transitionDuration: 300,
    particleEffects: true,
    screenShake: false,
  },
  sounds: {
    enabled: true,
    volume: 70,
    clickSound: true,
    hoverSound: true,
    successSound: true,
    errorSound: true,
  },
  widgets: {
    clock: { enabled: true, style: 'both', size: 'medium' },
    newsFeed: { enabled: true, speed: 7, source: 'tech' },
    logo: { enabled: true, type: 'seahawks', animated: true, size: 'medium' },
    systemStats: { enabled: true, metrics: ['cpu', 'memory'] },
  },
  layout: {
    menuStyle: 'dashboard',
    iconTheme: 'filled',
    density: 'comfortable',
    spacingMultiplier: 1.5,
    gapSize: 16,
  },
};

export const extremeTheme: Theme = {
  preset: 'extreme',
  ...baseTheme,
  visual: {
    textBrightness: 100,
    borderBrightness: 100,
    backgroundDarkness: 0,
    glowIntensity: 100,
    fontSize: 16,
    fontWeight: 900,
    lineHeight: 1.8,
    letterSpacing: 2,
    borderWidth: 4,
    borderGlow: true,
    transparency: 30,
    blurEffects: true,
  },
  animations: {
    enabled: true,
    speed: 2,
    hoverEffectsIntensity: 100,
    transitionDuration: 400,
    particleEffects: true,
    screenShake: true,
  },
  sounds: {
    enabled: true,
    volume: 100,
    clickSound: true,
    hoverSound: true,
    successSound: true,
    errorSound: true,
  },
  widgets: {
    clock: { enabled: true, style: 'both', size: 'large' },
    newsFeed: { enabled: true, speed: 10, source: 'all' },
    logo: { enabled: true, type: 'seahawks', animated: true, size: 'large' },
    systemStats: { enabled: true, metrics: ['cpu', 'memory', 'network', 'disk'] },
  },
  layout: {
    menuStyle: 'dashboard',
    iconTheme: 'duotone',
    density: 'comfortable',
    spacingMultiplier: 2,
    gapSize: 24,
  },
};

export const themePresets = {
  light: lightTheme,
  minimal: minimalTheme,
  standard: standardTheme,
  flashy: flashyTheme,
  extreme: extremeTheme,
};

export const defaultTheme = standardTheme;